# Generated by Django 5.1.7 on 2025-06-30 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('voiture', 'Voiture'), ('moto', 'Moto')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis', models.CharField(max_length=100)),
                ('immatriculation', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('no_fiche', models.CharField(blank=True, max_length=100, null=True)),
                ('couleur', models.CharField(blank=True, max_length=50, null=True)),
                ('cellulaire', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.client')),
                ('marque', models.ForeignKey(limit_choices_to={'categorie': 'moto'}, on_delete=django.db.models.deletion.CASCADE, to='vehicules.marque')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.proprietaire')),
                ('type_moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.typemoto')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis', models.CharField(max_length=100)),
                ('immatriculation', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('chrono', models.CharField(blank=True, max_length=100, null=True)),
                ('type_tech', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.client')),
                ('marque', models.ForeignKey(limit_choices_to={'categorie': 'voiture'}, on_delete=django.db.models.deletion.CASCADE, to='vehicules.marque')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.proprietaire')),
                ('type_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.typevehicule')),
            ],
        ),
    ]
