# Generated by Django 5.1.7 on 2025-06-30 19:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMoto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('chassis', models.CharField(max_length=100)),
                ('immatriculation', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('no_fiche', models.CharField(blank=True, max_length=100, null=True)),
                ('couleur', models.CharField(blank=True, max_length=50, null=True)),
                ('cellulaire', models.CharField(blank=True, max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vehicules.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marque', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'categorie': 'moto'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vehicules.marque')),
                ('proprietaire', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vehicules.proprietaire')),
                ('type_moto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vehicules.typemoto')),
            ],
            options={
                'verbose_name': 'historical moto',
                'verbose_name_plural': 'historical motos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVehicule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('chassis', models.CharField(max_length=100)),
                ('immatriculation', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('chrono', models.CharField(blank=True, max_length=100, null=True)),
                ('type_tech', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vehicules.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marque', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'categorie': 'voiture'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vehicules.marque')),
                ('proprietaire', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vehicules.proprietaire')),
                ('type_vehicule', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vehicules.typevehicule')),
            ],
            options={
                'verbose_name': 'historical vehicule',
                'verbose_name_plural': 'historical vehicules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
