# Generated by Django 5.1.7 on 2025-06-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0002_historicalmoto_historicalvehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmoto',
            name='chassis',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalmoto',
            name='immatriculation',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalvehicule',
            name='chassis',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalvehicule',
            name='immatriculation',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='moto',
            name='chassis',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='immatriculation',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='chassis',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
