# Generated by Django 5.1.7 on 2025-07-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0003_alter_historicalmoto_chassis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmoto',
            name='couleurs',
            field=models.CharField(blank=True, help_text='Liste des couleurs séparées par une virgule', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='couleurs',
            field=models.CharField(blank=True, help_text='Liste des couleurs séparées par une virgule', max_length=255, null=True),
        ),
    ]
