# Generated by Django 5.2.3 on 2025-07-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0007_update_categorie_voiture_to_vehicule'),
        ('vehicules', '0008_update_categorie_voiture_to_vehicule'),
    ]

    operations = [
    ]
