# Generated by Django 5.2.3 on 2025-07-03 13:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0009_merge_20250703_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie de véhicule',
                'verbose_name_plural': 'Catégories de véhicules',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['nom'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='historicalmoto',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Moto', 'verbose_name_plural': 'historical Motos'},
        ),
        migrations.AlterModelOptions(
            name='historicalvehicule',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Véhicule', 'verbose_name_plural': 'historical Véhicules'},
        ),
        migrations.AlterModelOptions(
            name='marque',
            options={'ordering': ['nom'], 'verbose_name': 'Marque', 'verbose_name_plural': 'Marques'},
        ),
        migrations.AlterModelOptions(
            name='moto',
            options={'ordering': ['-date', 'immatriculation'], 'verbose_name': 'Moto', 'verbose_name_plural': 'Motos'},
        ),
        migrations.AlterModelOptions(
            name='proprietaire',
            options={'ordering': ['nom'], 'verbose_name': 'Propriétaire', 'verbose_name_plural': 'Propriétaires'},
        ),
        migrations.AlterModelOptions(
            name='typemoto',
            options={'ordering': ['nom'], 'verbose_name': 'Type de moto', 'verbose_name_plural': 'Types de motos'},
        ),
        migrations.AlterModelOptions(
            name='typevehicule',
            options={'ordering': ['nom'], 'verbose_name': 'Type de véhicule', 'verbose_name_plural': 'Types de véhicules'},
        ),
        migrations.AlterModelOptions(
            name='vehicule',
            options={'ordering': ['-date', 'immatriculation'], 'verbose_name': 'Véhicule', 'verbose_name_plural': 'Véhicules'},
        ),
        migrations.AlterField(
            model_name='historicalmoto',
            name='immatriculation',
            field=models.CharField(db_index=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Format d'immatriculation invalide (ex: 1234FG03)", regex='^\\d{4}[A-Z]{2}\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='historicalmoto',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_maintenance', 'En maintenance')], default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalvehicule',
            name='immatriculation',
            field=models.CharField(db_index=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Format d'immatriculation invalide (ex: AA-123-AB)", regex='^[A-Z]{2}-\\d{3,4}-[A-Z]{2}$')]),
        ),
        migrations.AlterField(
            model_name='historicalvehicule',
            name='marque',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'categorie': 'vehicule'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vehicules.marque'),
        ),
        migrations.AlterField(
            model_name='historicalvehicule',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_maintenance', 'En maintenance')], default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='marque',
            name='categorie',
            field=models.CharField(choices=[('vehicule', 'Véhicule'), ('moto', 'Moto'), ('camion', 'Camion'), ('semi-remorque', 'Semi-remorque'), ('remorque', 'Remorque'), ('tracteur_routier', 'Tracteur routier'), ('tracteur_agricole', 'Tracteur agricole')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moto',
            name='immatriculation',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Format d'immatriculation invalide (ex: 1234FG03)", regex='^\\d{4}[A-Z]{2}\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='moto',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_maintenance', 'En maintenance')], default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='typemoto',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='typevehicule',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Format d'immatriculation invalide (ex: AA-123-AB)", regex='^[A-Z]{2}-\\d{3,4}-[A-Z]{2}$')]),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='marque',
            field=models.ForeignKey(limit_choices_to={'categorie': 'vehicule'}, on_delete=django.db.models.deletion.CASCADE, to='vehicules.marque'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_maintenance', 'En maintenance')], default='actif', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='marque',
            unique_together={('nom', 'categorie')},
        ),
    ]
