"""
Django settings for gestion_vehicules project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-z-77k3i^p&dd^&_*%e7g4ury-rjq%z$35y2adv+ae*y52dd(ed')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,immobilier-khoa.onrender.com').split(',')

# Configuration de sécurité pour la production
if not DEBUG:
    # HTTPS/SSL
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookies sécurisés
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Autres paramètres de sécurité
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Doit être avant django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'simple_history',
    'vehicules',
]

# Configuration pour forcer les migrations au démarrage
if os.environ.get('DJANGO_DEBUG', 'True').lower() == 'false':
    # En production, forcer les migrations au démarrage
    import subprocess
    import sys
    try:
        subprocess.run([sys.executable, 'manage.py', 'migrate', '--no-input'], check=True)
        print("✅ Migrations applied successfully at startup")
    except subprocess.CalledProcessError as e:
        print(f"❌ Error applying migrations: {e}")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'gestion_vehicules.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'vehicules.context_processors.dashboard_stats',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_vehicules.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Configuration de base de données - SQLite pour développement ET production
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Configuration des fichiers statiques
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Configuration pour Render
if not DEBUG:
    # Ajouter whitenoise pour servir les fichiers statiques
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    
    # Configuration simple et fiable pour whitenoise
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
    
    # S'assurer que STATIC_URL est défini
    if not STATIC_URL:
        STATIC_URL = '/static/'
    
    # Configuration de sécurité pour Render
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
else:
    # Configuration pour le développement
    STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration Jazzmin
JAZZMIN_SETTINGS = {
    # Titre de la page d'accueil
    "site_title": "Gestion Véhicules",
    "site_header": "🚗 Gestion Véhicules",
    "site_brand": "Gestion Véhicules",
    "site_logo": "images/logo.png",  # Logo dans la navbar
    "site_logo_classes": "img-fluid",
    "site_logo_height": "60px",
    "login_logo": "images/logo.png",  # Logo sur la page de connexion
    "login_logo_classes": "img-fluid",
    "login_logo_height": "80px",
    "welcome_sign": "Bienvenue dans votre système de gestion de véhicules",
    "copyright": "Gestion Véhicules Ltd",
    "search_model": ["vehicules.Vehicule", "vehicules.Moto", "vehicules.Client"],
    
    # Configuration de la sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Icônes personnalisées
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "vehicules.Vehicule": "fas fa-car",
        "vehicules.Moto": "fas fa-motorcycle",
        "vehicules.Client": "fas fa-users",
        "vehicules.Proprietaire": "fas fa-user-tie",
        "vehicules.Marque": "fas fa-industry",
        "vehicules.TypeVehicule": "fas fa-cogs",
        "vehicules.TypeMoto": "fas fa-tools",
    },
    
    # Configuration des modèles
    "order_with_respect_to": [
        "vehicules.Vehicule",
        "vehicules.Moto", 
        "vehicules.Client",
        "vehicules.Proprietaire",
        "vehicules.Marque",
        "vehicules.TypeVehicule",
        "vehicules.TypeMoto",
        "auth",
    ],
    
    # Personnalisation des listes
    "list_per_page": 25,
    
    # Configuration des couleurs
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "vehicules.vehicule": "collapsible",
        "vehicules.moto": "collapsible",
        "vehicules.client": "collapsible",
        "vehicules.proprietaire": "collapsible",
    },
    
    # Configuration des liens rapides
    "show_ui_builder": True,
    
    # Liens rapides personnalisés
    "custom_links": {
        "vehicules": [{
            "name": "Dashboard", 
            "url": "admin:index", 
            "icon": "fas fa-tachometer-alt",
        }],
    },
    
    # Widgets personnalisés
    "changeform_format": "horizontal_tabs",
    "show_ui_builder": True,
    
    # Configuration des messages
    "show_full_result_count": False,
    
    # Configuration de la recherche
    "search_model": ["vehicules.Vehicule", "vehicules.Moto", "vehicules.Client", "vehicules.Proprietaire"],
    
    # Configuration des actions
    "actions_show_confirmation": True,
    "actions_show_confirmation_modal": True,
    
    # Configuration des permissions
    "permissions": {
        "can_view_dashboard": "auth.view_user",
    },
}

# Configuration des thèmes Jazzmin
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}

LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/admin/'
